steps:
  - name: python
    entrypoint: python
    args: ["-m", "pip", "install", "--upgrade", "pip", "--user"]
  - name: python
    entrypoint: python
    args: ["-m", "pip", "install", "-r", "requirements.txt", "--user"]
    dir: 'pull_linkedin_shares_stats_daily'
  - name: python
    entrypoint: python
    args: ["-m", "pytest", "-v", "--cov"]
    secretEnv: ['TOKEN']
    dir: 'pull_linkedin_shares_stats_daily'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'pull_linkedin_shares_stats_daily_cicd', '--trigger-http', '--runtime', 'python311', '--entry-point', 'validate_http', '--timeout', '540s', '--memory', '512MB', '--set-secrets', 'TOKEN=projects/13410613811/secrets/linkedin_api_access_token:latest']
    dir: 'pull_linkedin_shares_stats_daily'
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/linkedin_api_access_token/versions/latest
    env: 'TOKEN'
